atlite:
  cutouts:
    europe-2010-era5:
      module: era5
      xs:
      - -12.0
      - 35.0
      years:
      - 2010
      - 2010
      ys:
      - 72.0
      - 33.0
  nprocesses: 4
costs:
  USD2013_to_EUR2013: 0.7532
  discountrate: 0.07
  emission_prices:
    co2: 0.0
  marginal_cost:
    H2: 0.0
    battery: 0.0
    hydro: 0.0
    offwind: 0.015
    onwind: 0.015
    solar: 0.01
  year: 2030
countries:
- DE
electricity:
  agg_p_nom_limits: data/agg_p_nom_minmax.csv
  co2base: 381464578.0
  co2limit: 77500000.0
  conventional_carriers:
  - CCGT
  - coal
  - lignite
  custom_powerplants: false
  extendable_carriers:
    Generator:
    - OCGT
    Link: []
    StorageUnit:
    - battery
    - H2
    Store: []
  max_hours:
    H2: 168
    battery: 6
  powerplants_filter: false
  voltages:
  - 220.0
  - 300.0
  - 380.0
enable:
  build_cutout: false
  build_natura_raster: false
  prepare_links_p_nom: false
  retrieve_cutout: false
  retrieve_databundle: false
  retrieve_natura_raster: true
lines:
  length_factor: 1.25
  s_max_pu: 0.7
  types:
    220.0: Al/St 240/40 2-bundle 220.0
    300.0: Al/St 240/40 3-bundle 300.0
    380.0: Al/St 240/40 4-bundle 380.0
  under_construction: zero
links:
  include_tyndp: true
  p_max_pu: 1.0
  under_construction: zero
load:
  scaling_factor: 1.0
logging:
  format: '%(levelname)s:%(name)s:%(message)s'
  level: INFO
renewable:
  hydro:
    PHS_max_hours: 6
    carriers:
    - ror
    - PHS
    - hydro
    clip_min_inflow: 1.0
    cutout: europe-2010-era5
    hydro_max_hours: energy_capacity_totals_by_country
  offwind-ac:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    corine:
    - 44
    - 255
    cutout: europe-2010-era5
    max_depth: 50
    max_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  offwind-dc:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    corine:
    - 44
    - 255
    cutout: europe-2010-era5
    max_depth: 50
    min_shore_distance: 30000
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
  onwind:
    capacity_per_sqkm: 3
    clip_p_max_pu: 0.01
    corine:
      distance: 1000
      distance_grid_codes:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      grid_codes:
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 31
      - 32
    cutout: europe-2010-era5
    natura: true
    potential: simple
    resource:
      method: wind
      turbine: Vestas_V112_3MW
  solar:
    capacity_per_sqkm: 1.7
    clip_p_max_pu: 0.01
    corine:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 26
    - 31
    - 32
    correction_factor: 0.854337
    cutout: europe-2010-era5
    natura: true
    potential: simple
    resource:
      method: pv
      orientation:
        azimuth: 180.0
        slope: 35.0
      panel: CSi
scenario:
  clusters:
  - 37
  - 128
  - 256
  - 512
  - 1024
  ll:
  - copt
  opts:
  - Co2L-3H
  sectors:
  - E
  simpl:
  - ''
snapshots:
  closed: left
  end: '2011-01-01'
  start: '2010-01-01'
solving:
  options:
    clip_p_max_pu: 0.01
    formulation: kirchhoff
    load_shedding: false
    max_iterations: 6
    min_iterations: 4
    noisy_costs: true
    skip_iterations: true
    track_iterations: false
  solver:
    AggFill: 0
    BarConvTol: 0.0001
    FeasibilityTol: 0.0001
    GURO_PAR_BARDENSETHRESH: 200
    PreDual: 0
    crossover: 0
    method: 2
    name: gurobi
    threads: 4
summary_dir: results
transformers:
  s_nom: 2000.0
  type: ''
  x: 0.1
tutorial: false
version: 0.1.0
